services:
  - type: web
    name: sanad-mauriai
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sanad-db
          property: connectionString
    autoDeploy: false

databases:
  - name: sanad-db
    plan: free
