services:
  - type: web
    name: sanad-mauriai
    runtime: node
    plan: free
    nodeVersion: 20
    buildCommand: npm ci && npm run build
    preDeployCommand: npm run db:push
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sanad-db
          property: connectionString
    autoDeploy: false

databases:
  - name: sanad-db
    plan: free
