services:
  - type: web
    name: sanad-mauriai
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false

databases:
  - name: sanad-db
    plan: free
